### ISSUE TITLE
Games added from EpicGames Store don't have spaces in the "name".  The names are also not editable.

### ISSUE THREAD

**Issue by kdliu86** [Alia5/GlosSI#197]
## Expected Behavior

Have spaces in the name (and Steam Grid then can find appropriate images).  Also have editable names.

## Actual Behavior

Games are added without spaces.  If you edit the name to have a space, it removes the space automatically.

## Steps to Reproduce the Problem

  1. Add a Epic Games game, game is added without spaces.
  2. Edit Name.
  3. Name edit is not completed.
...

## General Information

  - Version: 0.1.1.2
  - Platform: Win11
  - Application: GlosSIConfig

See discord issue as well.

**Comment by joaociocca** [comment]
Not only Epic. I just added Bluestacks' HD-Player.exe and it won't allow me to rename it either.

**Comment by Alia5** [comment]
Two completely seperate issues(!)

EGS-Games names only available in *PascalCase* should be worked around with this: https://github.com/Alia5/GlosSI/commit/f61971923db6d685cb7409d68b43389bda5d6fd8
Renaming shortcuts should be fixed by: https://github.com/Alia5/GlosSI/commit/244528669460d180b6fff3e0979bff8bb91ff7b9

Please try the latest snapshot build

**Comment by Alia5** [comment]
Since I haven't heard otherwise, I assume this is fixed

**Comment by joaociocca** [comment]
> Since I haven't heard otherwise, I assume this is fixed

Sorry for that, it's been a really full week here. I just got to update my GlosSI, and the spaces are... almost there. For simple names like "Death Stranding" and "Loop Hero", it works.
But on a more complex game, like "Alba - A Wildlife Adventure" or "LEGO Builder's Journey" there's something broken:

![image](https://user-images.githubusercontent.com/6473725/213946320-7c0b9e16-be11-4edb-9460-8a69887c2de5.png)
(from EGS)

![image](https://user-images.githubusercontent.com/6473725/213946319-8ecaa71b-dfc6-483b-9dbd-0fac736f22fd.png)
(from GlosSI)

Renaming, though, works as expected (see Alba's entry renamed below)
![image](https://user-images.githubusercontent.com/6473725/213946474-65a221dd-f627-47d4-b315-bc3e6026f8da.png)

**Comment by Alia5** [comment]
> But on a more complex game, like "Alba - A Wildlife Adventure" or "LEGO Builder's Journey" there's something broken:

With the current strategy on how EGS titles are resolved, this is pretty much a wontfix, sorry.  

Maybe a bit more detail on this:

The info of installed games gets read from `C:\ProgramData\Epic\UnrealEngineLauncher\LauncherInstalled.dat`    
This file contains all the info on installed EGS titles and to build the launch URL.  
However, regarding the name of installed titles, it contains little to no information, apart from the directory name of the individual installation locations.  
Therefore, the names get "approximated" from that directory name by only using the last path-segment and "un-camelcasify-ing" that string.

---

> (I just need to remember, now, how to add custom pics to those... maybe this could be an improvement? Perhaps an integration to [SGDBoop](https://www.steamgriddb.com/boop)/[Github](https://github.com/SteamGridDB/SGDBoop)?)

Steamgrid.db is integrated into GlosSI.  
Just make sure to get an API key from them (as for whatever stupid reason they require individual users to do this 🤦‍♂️) and then GlosSIConfig should show a button to load the images.

**Comment by joaociocca** [comment]
is there a log/verbose mode I can use to diagnose the Steamgrid integration? I must have forgotten about it earlier - I made an account there exactly to get the API key, it was already set on GlosSI... but here, it just keeps loading forever, no matter that I added only 2 shortcuts...

![image](https://user-images.githubusercontent.com/6473725/214050336-5e8199db-bc44-479a-bcf0-bf76a82a1170.png)

The text area scrolls up and down if I click and drag, but not horizontally so I'm unable to read it all - in case there's much more in there. I read that Steam installer wasn't found (expected, it's on D:), but I can't read what should I do to supply that information to GlosSI.

I imagined it was that I could drag and drop the Steam executable to GlosSI, but it won't work, attempting to drag it into GlosSI gives me the forbidden mouse icon.

**Comment by Alia5** [comment]
The text that is shown should just be the commandline output of the [steamgrid](https://github.com/boppreh/steamgrid) binary.
You can also just run it on its own.

I'm afraid I have to send you to their issue tracker

**Comment by Alia5** [comment]
Uh another thing I just remembered.  
the steamgrid binary works with your steam shortcuts directly.

So make sure that the shortcuts are in Steam and have the correct names there

**Comment by joaociocca** [comment]
I'm able to use their SGDBoop on the website fine, it even allows me to choose which non-steam game to apply their stuff to...

These three are customs from GlosSI (even though I'm still unable to make BlueStacks recognize the Steam controller...)

![image](https://user-images.githubusercontent.com/6473725/214077098-cff59ff8-fd85-49f3-8643-37fa18b067ba.png)

even the detailed page (for a non-Steam game, like Alba) is correctly themed ;)

![image](https://user-images.githubusercontent.com/6473725/214077320-7feae78c-fce7-4106-81c3-5bdf738aa847.png)
